Update talks_index.md
ClickHouse/clickhouse-presentations pull request #23
Opened 2021-09-02 11:36 UTC by filimonov

2021-09-02 13:29 UTC, alexey-milovidov requested changes
Missing CodeFest in Novosibirsk.

2021-09-08 14:14 UTC, filimonov commented
> Missing CodeFest in Novosibirsk.

?

Since last 'indexing' effort (bbd6e5aa86e7db156a9d346820ba938a4a2b4e28):

```
git diff --name-only bbd6e5aa86e7db156a9d346820ba938a4a2b4e28 | grep -v '/styles/' | grep -v '/shower/' | grep -v '/pictures/'
heisenbug2021/Heisenbug_2021_Using_SQLancer_to_test_ClickHoouse_and_other_DBMS_Manuel_Rigger_Yatsishin_Ilya.pdf
highload2021/LICENSE.md
highload2021/copier.pdf
highload2021/hash_tables/LICENSE.md
highload2021/hash_tables/index.html
highload2021/index.html
highload2021/perf-test.pdf
highload2021/video/memory_compressed_faster.ogv
highload2021/video/memory_compressed_slower.ogv
highload2021/video/memory_is_slower.ogv
highload2021/video/mergetree_vs_memory.ogv
meetup50/new_features/index.html
meetup51/DatabaseReplicated.pdf
meetup51/dictionaries/LICENSE.md
meetup51/dictionaries/index.html
meetup51/new_features/LICENSE.md
meetup51/new_features/index.html
meetup51/pg-ch-integration.pdf
meetup52/bi.pdf
meetup52/features/LICENSE.md
meetup52/features/index.html
meetup53/bigo.pdf
meetup53/ebay.pdf
meetup53/intro.pdf
meetup53/jit_in_clickhouse/LICENSE.md
meetup53/jit_in_clickhouse/index.html
meetup53/optimizations/LICENSE.md
meetup53/optimizations/index.html
meetup53/optimizations/video/memory_compressed_faster.ogv
meetup53/optimizations/video/memory_compressed_slower.ogv
meetup53/optimizations/video/memory_is_slower.ogv
meetup53/optimizations/video/mergetree_vs_memory.ogv
meetup53/tencent.pdf
meetup54/keeper.pdf
meetup54/signoz.pdf
original_website/benchmark.html
original_website/benchmark_hardware.html
percona2021/LICENSE.md
percona2021/index.html
percona2021/projections.pdf
pgday2021/postgresql-integration-kssenii.pdf
talks_index.md
zero_cost_conf/hash_tables/c++_zero_cost_hash_tables.pdf
zero_cost_conf/memcpy/LICENSE.md
zero_cost_conf/memcpy/index.html
```

Since 3b4993216a0f0022c9225485a913f079e0d36a76
```
git diff --name-only 3b4993216a0f0022c9225485a913f079e0d36a76 | grep -v '/styles/' | grep -v '/shower/' | grep -v '/pictures/'
```

can't see it. :|

2021-09-08 15:10 UTC, filimonov commented
Ok. Found the info, but presentation was not uploaded here - linked it from yandex.disk (it's seems the same as in highload, with some extra styling).

2021-09-08 17:30 UTC, alexey-milovidov approved these changes

2021-09-08 17:30 UTC, merged